version: "3.9"
services:
  webapp:
    container_name: "node-app"
    build:
      context: ./node-app
      dockerfile: Dockerfile
    volumes:
      - ./node-app/.:/app
    ports:
      - 3001:3001
    depends_on:
      - mongoDB
  mongoDB:
    image: mongo
    ports:
      - 27018:27017
